services:
  server:
    build: .
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:8080"
    volumes:
      - .:/usr/src/app
    command: go run cmd/main.go
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
  migrate:
    image: migrate/migrate
    env_file:
      - .env
    volumes:
      - ${MIGRATIONS_PATH}:/migrations
    command:
      [
        "-path", "/migrations",
        "-database",
        "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable",
        "up"
      ]
    depends_on:
      - db

volumes:
  postgres-db: